import os
import shutil
import random
from solution import recursive_max

TEST_CASES_DIR = './test_cases'
INPUTS_DIR = f'{TEST_CASES_DIR}/input'
OUTPUTS_DIR = f'{TEST_CASES_DIR}/output'


def get_input():
    population = [random.randint(0, 199) for i in range(20)]
    A = random.choices(population=population, k=20)
    return A


def save_input_case(case_id, *inputs):
    with open(f'{INPUTS_DIR}/input{case_id}.txt', 'w') as fp:
        for el in inputs:
            fp.write(f'{el}\n')


def save_output_case(case_id, *outputs):
    with open(f'{OUTPUTS_DIR}/output{case_id}.txt', 'w') as fp:
        for el in outputs:
            fp.write(f'{el}\n')


def main():
    os.makedirs(INPUTS_DIR, exist_ok=True)
    os.makedirs(OUTPUTS_DIR, exist_ok=True)

    def handle_case(*_, **params):
        case_id = params['case_id']
        A = params['A']

        A_str = ' '.join(str(el) for el in A)
        _max = recursive_max(A)

        save_input_case(case_id, A_str)
        save_output_case(case_id, _max)

    # autogenerated test cases
    for i in range(37):
        case_id = "{:02d}".format(i)
        A = get_input()
        handle_case(case_id=case_id, A=A)


    # the rest are created manually for edge cases
    i += 1
    handle_case(case_id="{:02d}".format(i), A=[1])

    i += 1
    handle_case(case_id="{:02d}".format(i), A=list(range(20)))

    i += 1
    handle_case(case_id="{:02d}".format(i), A=[])


    # zip the test cases folder
    shutil.make_archive(TEST_CASES_DIR, 'zip', TEST_CASES_DIR)


if __name__ == '__main__':
    main()